
language: node_js
node_js: [node]

before_install:
  - if [[ $TRAVIS_OS_NAME == "linux" ]]; then export CXX=g++-4.8; fi

cache:
  yarn: true

env:
  matrix:
    - TEST_TYPE=test
    - TEST_TYPE=lint

script:
  - yarn build
  - yarn $TEST_TYPE
